name: pertemuan12json
description: Demo JSON, SharedPreferences, path_provider, encryption, REST API
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  shared_preferences: ^2.2.2
  path_provider: ^2.1.5
  path: ^1.8.3
  encrypt: ^5.0.1
  json_annotation: ^4.8.1   # ← versi stabil untuk Dart 2.17–2.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3       # ← versi stabil untuk Dart 2.17–2.19
  json_serializable: ^6.7.0  # ← versi terakhir yang support Dart 2
